### 1.异常处理
- Golang没有结构化异常，使用panic抛出错误，recover捕获错误
- 异常的使用场景简单描述: Go中可以抛出一个panic异常，然后再defer中通过recover捕获这个异常，然后正常护理

### 2.panic
```
1、内置函数
2、假如函数F中书写了panic语句，会终止其后要执行的代码，在panic所在函数F内如果存在要执行的defer函数列表，按照defer的逆序执行
3、返回函数F的调用者G，在G中，调用函数F语句之后的代码不会执行，假如函数G中存在要执行的defer函数列表，按照defer的逆序执行
4、直到goroutine整个退出，并报告错误
```

### 3recover
```
1、内置函数
2、用来控制一个goroutine的panicking行为，捕获panic，从而影响应用的行为
3、一般的调用建议
    a). 在defer函数中，通过recever来终止一个goroutine的panicking过程，从而恢复正常代码的执行
    b). 可以获取通过panic传递的error
```

### 4.需要注意的
```
1.利用recover处理panic指令，defer 必须放在 panic 之前定义，另外 recover 只有在 defer 调用的函数中才有效。
    否则当panic时，recover无法捕获到panic，无法防止panic扩散。
2.recover 处理异常后，逻辑并不会恢复到 panic 那个点去，函数跑到 defer 之后的那个点。
3.多个 defer 会形成 defer 栈，后定义的 defer 语句会被最先调用。
```

### 5.例子
- 由于panic、recover参数类型为interface{}因此可抛出人任意类型的对象
- func panic(v interface{})
- func recover() interface{}
```go
package main

func test(){
    // 处理panic
	defer func() {
		if err := recover(); err != nil{
			println(err.(string))	// 将interface{}转型为具体类型(没看懂)
		}
	}()
    
	// 恐慌
	panic("panic error")
}

func main(){
	// 最终输出
	// panic error!
	test()
}
```

### 6.向已关闭的通道发送数据会引发panic
```go
package main

import "fmt"

func main() {
	defer func() {
		if err := recover(); err != nil{
			fmt.Println(err)
		}
	}()

	var ch chan int = make(chan int, 4)
	// 关闭通道
	close(ch)
	// 向关闭的通道发送数据
	ch <- 1
    
    // 输出结果
}
```

### 7.一个例子
- 捕获函数 recover 只有在延迟调用内直接调用才会终止错误，否则总是返回 nil。
- 任何未捕获的错误都会沿调用堆栈向外传递。
```go
package main

import "fmt"

// 没看懂
func test1(){

	// 闭包内有效
	defer func() {
		fmt.Println(recover())		// 有效
	}()

	defer recover()					// 无效

	defer fmt.Println(recover())	// 无效

	// 为什么闭包再闭包内无效呢
	defer func() {
		func(){
			println("defer inner")
			recover()
		}()
	}()

	// 触发恐慌
	panic("test panic")
    
    /*
        输出
        defer inner
        <nil>
        test panic
    */

}
```

### 8.使用延迟你那个函数或下面这样都是有效的
```go
package main

import "fmt"

func except(){
	fmt.Println(recover())
}

func test2(){
	defer except()
	panic("test panic")
}

func main() {
	test2()
}
```

### 9.如过需要保护代码段，可以将代码块重构成匿名函数，如此可确保后续代码被执行
```go
package main

import "fmt"

func test3(x, y int){
	var z int

	func(){
		defer func() {
			if recover() != nil{
				z = 0
			}
		}()

		panic("test panic")
		z = x / y
		return
	}()
    
    // 这里会执行
	fmt.Printf("x / y = %d\n", z)
}

func main()  {
	test3(2,1)
}
```